// One-time bake: convert me.jpg into ASCII frames embedded as a TS module.
// Run: bun run scripts/bake-portrait.ts <path-to-image>
import { Jimp } from "jimp";
import { writeFileSync } from "node:fs";

const SRC = process.argv[2] ?? `${process.env.HOME}/personalv8/public/me.jpg`;
const COLS = 46;
const CHAR_ASPECT = 0.42; // terminal cells are ~2x taller than wide

// bright -> dark ramp (inverted): dark subject becomes dense "ink" on black bg,
// the busy bright background falls away to empty space — milst-style portrait.
const RAMP = "@80GCLft1i;:,. ";

const img = await Jimp.read(SRC);

// crop to subject (head + shoulders), dropping the window frame (left) and
// most of the Tokyo Tower (right) so the portrait reads cleanly.
const iw = img.bitmap.width;
const ih = img.bitmap.height;
const cx = Math.round(iw * 0.2);
const cy = Math.round(ih * 0.22);
const cw = Math.round(iw * 0.62);
const ch = Math.round(ih * 0.74);
img.crop({ x: cx, y: cy, w: cw, h: ch });
img.contrast(0.18);

const w = img.bitmap.width;
const h = img.bitmap.height;
const rows = Math.round((COLS * (h / w)) * CHAR_ASPECT);

img.resize({ w: COLS, h: rows });

// per-pixel luminance grid (0..1)
const lum: number[][] = [];
for (let y = 0; y < rows; y++) {
  const line: number[] = [];
  for (let x = 0; x < COLS; x++) {
    const idx = (y * COLS + x) * 4;
    const r = img.bitmap.data[idx];
    const g = img.bitmap.data[idx + 1];
    const b = img.bitmap.data[idx + 2];
    line.push((0.299 * r + 0.587 * g + 0.114 * b) / 255);
  }
  lum.push(line);
}

// normalize contrast a touch
let min = 1, max = 0;
for (const row of lum) for (const v of row) { if (v < min) min = v; if (v > max) max = v; }
const norm = (v: number) => (max > min ? (v - min) / (max - min) : v);

function frame(gamma: number): string[] {
  return lum.map((row) =>
    row
      .map((v) => {
        const g = Math.pow(norm(v), gamma);
        return RAMP[Math.min(RAMP.length - 1, Math.max(0, Math.round(g * (RAMP.length - 1))))];
      })
      .join(""),
  );
}

// two slightly different gammas -> gentle "breathing" flicker between frames
const frames = [frame(1.15), frame(1.0), frame(1.3)];

const out =
  `// AUTO-GENERATED by scripts/bake-portrait.ts — do not edit by hand.\n` +
  `// Source: me.jpg, ${COLS}x${rows} ASCII.\n` +
  `export const PORTRAIT_COLS = ${COLS};\n` +
  `export const PORTRAIT_ROWS = ${rows};\n` +
  `export const PORTRAIT_FRAMES: string[][] = ${JSON.stringify(frames, null, 0)};\n` +
  `// luminance grid (0..1) for the scan-beam shading\n` +
  `export const PORTRAIT_LUM: number[][] = ${JSON.stringify(lum.map((r) => r.map((v) => Math.round(norm(v) * 100) / 100)))};\n`;

writeFileSync(`${import.meta.dir}/../ascii-art.ts`, out);
console.log(`Wrote ascii-art.ts — ${COLS}x${rows}, ${frames.length} frames`);
// preview
for (const line of frames[0]) console.log(line);
