// One-time bake: convert a person-cutout PNG (transparent background, e.g. from
// scripts/segment.swift) into ASCII frames embedded as a TS module.
//
//   swiftc -O scripts/segment.swift -o /tmp/segment
//   /tmp/segment ~/personalv8/public/me.jpg /tmp/me-cutout.png
//   bun run scripts/bake-portrait.ts /tmp/me-cutout.png
import { Jimp } from "jimp";
import { writeFileSync } from "node:fs";

const SRC = process.argv[2] ?? "/tmp/me-cutout.png";
const COLS = 44;
const CHAR_ASPECT = 0.46; // terminal cells are ~2x taller than wide
const ALPHA_CUT = 110; // alpha below this = background

// dark -> light ramp for the person; index 0 is the densest "ink".
// Brightest person pixel still maps to '.', so the full silhouette stays visible.
const RAMP = "@8&GCLft1i;:,.";

const img = await Jimp.read(SRC);
const iw = img.bitmap.width;
const ih = img.bitmap.height;
const A = (x: number, y: number) => img.bitmap.data[(y * iw + x) * 4 + 3];

// auto-crop to the person's alpha bounding box (+ small padding)
let minX = iw, minY = ih, maxX = 0, maxY = 0;
for (let y = 0; y < ih; y++)
  for (let x = 0; x < iw; x++)
    if (A(x, y) >= ALPHA_CUT) {
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
const pad = Math.round(iw * 0.03);
minX = Math.max(0, minX - pad);
minY = Math.max(0, minY - pad);
maxX = Math.min(iw - 1, maxX + pad);
maxY = Math.min(ih - 1, maxY + pad);
img.crop({ x: minX, y: minY, w: maxX - minX + 1, h: maxY - minY + 1 });
img.contrast(0.12);

const w = img.bitmap.width;
const h = img.bitmap.height;
const rows = Math.round(COLS * (h / w) * CHAR_ASPECT);
img.resize({ w: COLS, h: rows });

// build luminance + alpha grids
const lum: number[][] = [];
const alpha: number[][] = [];
for (let y = 0; y < rows; y++) {
  const lrow: number[] = [];
  const arow: number[] = [];
  for (let x = 0; x < COLS; x++) {
    const i = (y * COLS + x) * 4;
    const r = img.bitmap.data[i];
    const g = img.bitmap.data[i + 1];
    const b = img.bitmap.data[i + 2];
    lrow.push((0.299 * r + 0.587 * g + 0.114 * b) / 255);
    arow.push(img.bitmap.data[i + 3]);
  }
  lum.push(lrow);
  alpha.push(arow);
}

// normalize contrast across person pixels only
let min = 1, max = 0;
for (let y = 0; y < rows; y++)
  for (let x = 0; x < COLS; x++)
    if (alpha[y][x] >= ALPHA_CUT) {
      const v = lum[y][x];
      if (v < min) min = v;
      if (v > max) max = v;
    }
const norm = (v: number) => (max > min ? (v - min) / (max - min) : v);

function frame(gamma: number): string[] {
  const out: string[] = [];
  for (let y = 0; y < rows; y++) {
    let line = "";
    for (let x = 0; x < COLS; x++) {
      if (alpha[y][x] < ALPHA_CUT) { line += " "; continue; }
      const g = Math.pow(norm(lum[y][x]), gamma);
      line += RAMP[Math.min(RAMP.length - 1, Math.max(0, Math.round(g * (RAMP.length - 1))))];
    }
    out.push(line.replace(/\s+$/u, "")); // trim trailing blanks
  }
  return out;
}

// gentle gamma "breathing" between frames for a living, CRT-ish feel
const frames = [frame(1.0), frame(0.85), frame(1.2)];

const out =
  `// AUTO-GENERATED by scripts/bake-portrait.ts — do not edit by hand.\n` +
  `// Source: person cutout, ${COLS}x${rows} ASCII.\n` +
  `export const PORTRAIT_COLS = ${COLS};\n` +
  `export const PORTRAIT_ROWS = ${rows};\n` +
  `export const PORTRAIT_FRAMES: string[][] = ${JSON.stringify(frames)};\n`;

writeFileSync(`${import.meta.dir}/../ascii-art.ts`, out);
console.log(`Wrote ascii-art.ts — ${COLS}x${rows}, ${frames.length} frames`);
for (const line of frames[0]) console.log(line);
